name: Context practice
on: push
jobs:
  show-info:
    runs-on: ubuntu-latest
    env:
      secret_variable: ${{ secrets.SECRET_TEST }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: show repository info!
        run: echo "Se ejecuta en la ref ${{ github.ref }}"
      - run: echo "Se disparó por el evento ${{ github.event }}"
      - run: echo "Disparado por ${{ github.actor }}"
      - run: echo "Estado del job ${{ job.status }}"
      - run: echo "Commit ${{ github.sha }}"
      - run: echo "Runner ${{ runner.name }}"
      - run: echo "SO del runner ${{ runner.os }}"
      - name: Validar los secrets
        run: python validate-secret.py
