name: hello-world
on: [push]
jobs:
  hello-world: 
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: Super linter
          uses: super-linter/super-linter@v7.3.0
          env:
            # To report GitHub Actions status checks
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
