name: Triggers

on:
  push:
    branches:
      - main
      - releases/**
  pull_request:
    branches:
      - main
    types:
      - opened
  schedule:
    - cron: '30 * * * *'
  
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
